### ISSUE TITLE
Any updates planned?

### ISSUE THREAD

**Issue by mrghosti3** [Narigo/keepass-diff#54]
Libraries (below) have received updates:
- keepass-rs: `0.4.10` => `0.6.1`
- rpassword: `5.0.1` => `7.2.0`

Plus it is unclear which edition the project is using. Maybe I could help with some stuff?

**Comment by Narigo** [comment]
Hi @mrghosti3 - I haven't come around to update to the newer versions. I know @sseemayer even mentioned me to update and give feedback, but I was lacking time to put into this tool.

If you want to try and update, you can give it a go, I don't think I'm able to do anything in this project for the next 2 weeks at least.

**Comment by mrghosti3** [comment]
Oki and is there any tips on how I could approach testing or about pull request submissions?

**Comment by Narigo** [comment]
I have written some tests in the `run-tests.sh` shell script. I haven't come around to create a GitHub action that builds and runs this though yet. I suppose creating an action for tests and creating binaries is probably a good idea to do next...

**Comment by Narigo** [comment]
Sorry for not getting back to this lately, had lots of stuff on my plate. I have done some work on updating crates before your PRs came in, but I remember being stuck when trying to update keepass-rs. I've added some [tests for keepass-rs that showcased my issue](https://github.com/sseemayer/keepass-rs/pull/180) and from the looks it should be fixed by now. I need to check this again - I hope I can get back to this weekend.

**Comment by Narigo** [comment]
Finally got around to finalize the obfuscation feature for the passwords and updated the dependencies as well (see #66). Thanks for pushing me to do it @mrghosti3 !
